[images]
  remote_images = ["https://ext.same-assets.com/*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_HOST = "netlify.app"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
